# Generated by Django 5.2.8 on 2025-11-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='show_time',
            field=models.DateTimeField(default='2025-01-01 00:00', help_text='The selected date and time of the movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('used', 'Used'), ('unused', 'Unused')], default='unused', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='theater_name',
            field=models.CharField(default='Lubbock Grand Cinema', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='movie',
            name='price_per_ticket',
            field=models.DecimalField(decimal_places=2, default=12.5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
